#! /bin/sh
### BEGIN INIT INFO
# Provides:          pipplware
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: pipplware Daemon
# Description:       pipplware Daemon
### END INIT INFO

# Author: Filipe Teixeira <teixeiras@gmail.com>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="PIPPlware Daemon"
NAME=pipplware
STARTAS=/usr/bin/pipplware
DAEMON=/bin/sh
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Defaults
ENABLED=0
USER=root
NICE=0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions


case "$1" in
  start)
  [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
  /usr/bin/pipplware &
  ;;
  stop)
  [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
  sudo killall pipplware
  ;;
  status)
  status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
  ;;
  restart|force-reload)
  ;;
  *)
  echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
  exit 3
  ;;
esac

: